/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        t: {
          bg:           '#FAFAF7',
          surface:      '#FFFFFF',
          surface2:     '#F4F2EB',
          border:       '#E7E4D9',
          text:         '#121212',
          textSec:      '#6B6B70',
          textTer:      '#A3A3A3',
          textOnDark:   '#FFFFFF',
          action:       '#0A0A0A',
          actionPressed:'#2B2B2B',
          gold:         '#D4AF37',
          goldBright:   '#E8C766',
          goldDeep:     '#A8842A',
          goldForeground: '#0A0A0A',
          goldBg:       '#FBF6E3',
          success:      '#22C55E',
          successBg:    '#E8F5EC',
          danger:       '#EF4444',
          dangerBg:     '#FDECEC',
          warning:      '#F59E0B',
          warningBg:    '#FEF3E2',
          dark:         '#0A0A0A',
          darkSurface:  '#1C1C1C',
        },
        gold: {
          50: '#fdf9ec',
          100: '#f9efca',
          200: '#f3dd90',
          300: '#ecc84d',
          400: '#e4b528',
          500: '#D4AF37',
          600: '#b8911a',
          700: '#936e16',
          800: '#795818',
          900: '#67481a',
          950: '#3c270a',
        },
        empire: {
          black: '#0A0A0A',
          charcoal: '#1C1C1C',
          gold: '#D4AF37',
          white: '#FFFFFF',
          success: '#00C853',
          warning: '#FF9800',
          error: '#D32F2F',
        },
        surface: {
          100: '#F8F8F8',
          200: '#F0F0F0',
          300: '#E8E8E8',
          400: '#D0D0D0',
        },
      },
      fontFamily: {
        sans: ['Inter_400Regular', 'System'],
        medium: ['Inter_500Medium', 'System'],
        semibold: ['Inter_600SemiBold', 'System'],
        bold: ['Inter_700Bold', 'System'],
        black: ['Inter_900Black', 'System'],
        heading: ['PlusJakartaSans_700Bold', 'System'],
        headingExtra: ['PlusJakartaSans_800ExtraBold', 'System'],
      },
      borderRadius: {
        sm: 10,
        md: 16,
        lg: 24,
        '2xl': 16,
        '3xl': 24,
        '4xl': 32,
      },
    },
  },
  plugins: [],
};
